# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build-php71:
    docker:
      - image: circleci/php:7.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - php71-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - php71-dependencies-

      - run:
          name: Display PHP information
          command: |
            php -v
            composer --version

      - run:
          name: Install project dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: php71-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Run Unit tests
          command: vendor/bin/phpunit

      - run:
          name: Run CodeStyle tests
          command: vendor/bin/phpcs -s --report-width=200 src/

  build-php72:
    docker:
      - image: circleci/php:7.2-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - php72-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - php72-dependencies-

      - run:
          name: Display PHP information
          command: |
            php -v
            composer --version

      - run:
          name: Install project dependencies
          command: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: php72-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Run Unit tests
          command: vendor/bin/phpunit

workflows:
  version: 2
  build:
    jobs:
      - build-php71
      - build-php72
